
# Write titan-engine.js using a different approach - smaller chunks
with open('/mnt/agents/output/titan-engine.js', 'w', encoding='utf-8') as f:
    f.write('''// Titan Engine v1.0 - The Brain
const TitanEngine = {
  player: {
    name: "CodysseyHero", level: 1, xp: 0, streak: 0,
    languagesUnlocked: ["py"], gitSkillsUnlocked: ["init"],
    badges: ["first-step"]
  },

  languagesDB: [
    { id: "py", name: "Python", icon: "🐍", diff: 1, cat: "Scripting", lessons: 50, unlocked: true },
    { id: "js", name: "JavaScript", icon: "🦕", diff: 2, cat: "Web", lessons: 60, unlocked: false },
    { id: "html", name: "HTML5", icon: "📄", diff: 1, cat: "Web", lessons: 30, unlocked: true },
    { id: "css", name: "CSS3", icon: "🎨", diff: 1, cat: "Web", lessons: 35, unlocked: true },
    { id: "scratch", name: "Scratch", icon: "🧩", diff: 1, cat: "Visual", lessons: 25, unlocked: true },
    { id: "java", name: "Java", icon: "☕", diff: 3, cat: "OOP", lessons: 55, unlocked: false },
    { id: "cpp", name: "C++", icon: "⚡", diff: 4, cat: "Systems", lessons: 70, unlocked: false },
    { id: "csharp", name: "C#", icon: "🎯", diff: 3, cat: "OOP", lessons: 50, unlocked: false },
    { id: "php", name: "PHP", icon: "🐘", diff: 2, cat: "Web", lessons: 40, unlocked: false },
    { id: "ruby", name: "Ruby", icon: "💎", diff: 2, cat: "Scripting", lessons: 45, unlocked: false },
    { id: "swift", name: "Swift", icon: "📱", diff: 3, cat: "Mobile", lessons: 50, unlocked: false },
    { id: "kotlin", name: "Kotlin", icon: "🎯", diff: 3, cat: "Mobile", lessons: 48, unlocked: false },
    { id: "go", name: "Go", icon: "🔒", diff: 3, cat: "Cloud", lessons: 45, unlocked: false },
    { id: "ts", name: "TypeScript", icon: "📘", diff: 3, cat: "Web", lessons: 45, unlocked: false },
    { id: "sql", name: "SQL", icon: "🗄️", diff: 2, cat: "Database", lessons: 35, unlocked: false },
    { id: "rust", name: "Rust", icon: "🦀", diff: 5, cat: "Systems", lessons: 65, unlocked: false },
    { id: "c", name: "C", icon: "🔧", diff: 4, cat: "Systems", lessons: 60, unlocked: false },
    { id: "scala", name: "Scala", icon: "🔴", diff: 4, cat: "Functional", lessons: 55, unlocked: false },
    { id: "haskell", name: "Haskell", icon: "λ", diff: 5, cat: "Functional", lessons: 60, unlocked: false },
    { id: "elixir", name: "Elixir", icon: "💧", diff: 4, cat: "Functional", lessons: 50, unlocked: false },
    { id: "clojure", name: "Clojure", icon: "🔮", diff: 4, cat: "Functional", lessons: 50, unlocked: false },
    { id: "erlang", name: "Erlang", icon: "📡", diff: 4, cat: "Functional", lessons: 50, unlocked: false },
    { id: "r", name: "R", icon: "📊", diff: 3, cat: "Data Science", lessons: 45, unlocked: false },
    { id: "matlab", name: "MATLAB", icon: "🔢", diff: 3, cat: "Data Science", lessons: 40, unlocked: false },
    { id: "dart", name: "Dart", icon: "🎯", diff: 2, cat: "Mobile", lessons: 40, unlocked: false },
    { id: "lua", name: "Lua", icon: "🌙", diff: 2, cat: "Scripting", lessons: 35, unlocked: false },
    { id: "perl", name: "Perl", icon: "🐪", diff: 3, cat: "Scripting", lessons: 40, unlocked: false },
    { id: "shell", name: "Shell/Bash", icon: "🐚", diff: 2, cat: "Scripting", lessons: 35, unlocked: false },
    { id: "powershell", name: "PowerShell", icon: "💻", diff: 2, cat: "Scripting", lessons: 35, unlocked: false },
    { id: "groovy", name: "Groovy", icon: "🎸", diff: 3, cat: "JVM", lessons: 40, unlocked: false },
    { id: "julia", name: "Julia", icon: "🔬", diff: 3, cat: "Data Science", lessons: 45, unlocked: false },
    { id: "fortran", name: "Fortran", icon: "📜", diff: 4, cat: "Scientific", lessons: 45, unlocked: false },
    { id: "cobol", name: "COBOL", icon: "🏛️", diff: 3, cat: "Enterprise", lessons: 40, unlocked: false },
    { id: "vba", name: "VBA", icon: "📊", diff: 2, cat: "Office", lessons: 30, unlocked: false },
    { id: "abap", name: "ABAP", icon: "🏢", diff: 3, cat: "Enterprise", lessons: 40, unlocked: false },
    { id: "sas", name: "SAS", icon: "📈", diff: 3, cat: "Data Science", lessons: 40, unlocked: false },
    { id: "fsharp", name: "F#", icon: "🔷", diff: 4, cat: "Functional", lessons: 50, unlocked: false },
    { id: "ocaml", name: "OCaml", icon: "🐫", diff: 4, cat: "Functional", lessons: 50, unlocked: false },
    { id: "prolog", name: "Prolog", icon: "🧠", diff: 4, cat: "Logic", lessons: 45, unlocked: false },
    { id: "lisp", name: "Lisp", icon: "🍃", diff: 4, cat: "Functional", lessons: 50, unlocked: false },
    { id: "scheme", name: "Scheme", icon: "🔷", diff: 4, cat: "Functional", lessons: 45, unlocked: false },
    { id: "smalltalk", name: "Smalltalk", icon: "💬", diff: 3, cat: "OOP", lessons: 40, unlocked: false },
    { id: "delphi", name: "Delphi", icon: "🏛️", diff: 3, cat: "Desktop", lessons: 40, unlocked: false },
    { id: "pascal", name: "Pascal", icon: "📐", diff: 2, cat: "Education", lessons: 35, unlocked: false },
    { id: "basic", name: "BASIC", icon: "📺", diff: 1, cat: "Education", lessons: 25, unlocked: false },
    { id: "logo", name: "Logo", icon: "🐢", diff: 1, cat: "Education", lessons: 20, unlocked: false },
    { id: "algol", name: "ALGOL", icon: "📜", diff: 3, cat: "Historical", lessons: 30, unlocked: false },
    { id: "apl", name: "APL", icon: "⍝", diff: 5, cat: "Array", lessons: 50, unlocked: false },
    { id: "forth", name: "Forth", icon: "🔧", diff: 4, cat: "Stack", lessons: 45, unlocked: false },
    { id: "racket", name: "Racket", icon: "🎾", diff: 3, cat: "Functional", lessons: 40, unlocked: false },
    { id: "crystal", name: "Crystal", icon: "💎", diff: 3, cat: "Systems", lessons: 40, unlocked: false },
    { id: "nim", name: "Nim", icon: "🎯", diff: 3, cat: "Systems", lessons: 40, unlocked: false },
    { id: "zig", name: "Zig", icon: "⚡", diff: 4, cat: "Systems", lessons: 45, unlocked: false },
    { id: "v", name: "V Lang", icon: "✌️", diff: 3, cat: "Systems", lessons: 40, unlocked: false },
    { id: "odin", name: "Odin", icon: "🐦", diff: 4, cat: "Systems", lessons: 45, unlocked: false },
    { id: "pony", name: "Pony", icon: "🐴", diff: 4, cat: "Actor", lessons: 45, unlocked: false },
    { id: "reason", name: "ReasonML", icon: "🧠", diff: 4, cat: "Functional", lessons: 45, unlocked: false },
    { id: "elm", name: "Elm", icon: "🌳", diff: 3, cat: "Frontend", lessons: 40, unlocked: false },
    { id: "purescript", name: "PureScript", icon: "📜", diff: 4, cat: "Functional", lessons: 45, unlocked: false },
    { id: "idris", name: "Idris", icon: "🔍", diff: 5, cat: "Dependent Types", lessons: 50, unlocked: false },
    { id: "agda", name: "Agda", icon: "📐", diff: 5, cat: "Dependent Types", lessons: 50, unlocked: false },
    { id: "coq", name: "Coq", icon: "🐔", diff: 5, cat: "Proof", lessons: 50, unlocked: false },
    { id: "lean", name: "Lean", icon: "📏", diff: 5, cat: "Proof", lessons: 50, unlocked: false },
    { id: "solidity", name: "Solidity", icon: "⛓️", diff: 3, cat: "Blockchain", lessons: 40, unlocked: false },
    { id: "vyper", name: "Vyper", icon: "🐍", diff: 3, cat: "Blockchain", lessons: 35, unlocked: false },
    { id: "move", name: "Move", icon: "📦", diff: 4, cat: "Blockchain", lessons: 40, unlocked: false },
    { id: "cairo", name: "Cairo", icon: "🏺", diff: 4, cat: "Blockchain", lessons: 45, unlocked: false },
    { id: "wasm", name: "WebAssembly", icon: "⚙️", diff: 4, cat: "Web", lessons: 45, unlocked: false },
    { id: "graphql", name: "GraphQL", icon: "📊", diff: 3, cat: "API", lessons: 35, unlocked: false },
    { id: "json", name: "JSON", icon: "📋", diff: 1, cat: "Data", lessons: 15, unlocked: true },
    { id: "xml", name: "XML", icon: "📄", diff: 2, cat: "Data", lessons: 20, unlocked: false },
    { id: "yaml", name: "YAML", icon: "📑", diff: 1, cat: "Config", lessons: 15, unlocked: false },
    { id: "toml", name: "TOML", icon: "⚙️", diff: 1, cat: "Config", lessons: 15, unlocked: false },
    { id: "regex", name: "Regex", icon: "🔍", diff: 3, cat: "Pattern", lessons: 30, unlocked: false },
    { id: "markdown", name: "Markdown", icon: "📝", diff: 1, cat: "Docs", lessons: 15, unlocked: true },
    { id: "latex", name: "LaTeX", icon: "📐", diff: 3, cat: "Docs", lessons: 35, unlocked: false },
    { id: "asciidoc", name: "AsciiDoc", icon: "📖", diff: 2, cat: "Docs", lessons: 25, unlocked: false },
    { id: "dockerfile", name: "Dockerfile", icon: "🐳", diff: 2, cat: "DevOps", lessons: 25, unlocked: false },
    { id: "terraform", name: "Terraform", icon: "🏗️", diff: 3, cat: "DevOps", lessons: 35, unlocked: false },
    { id: "ansible", name: "Ansible", icon: "🤖", diff: 2, cat: "DevOps", lessons: 30, unlocked: false },
    { id: "puppet", name: "Puppet", icon: "🎭", diff: 3, cat: "DevOps", lessons: 35, unlocked: false },
    { id: "chef", name: "Chef", icon: "👨‍🍳", diff: 3, cat: "DevOps", lessons: 35, unlocked: false },
    { id: "jenkins", name: "Jenkinsfile", icon: "🔧", diff: 3, cat: "DevOps", lessons: 30, unlocked: false },
    { id: "gitlab", name: "GitLab CI", icon: "🦊", diff: 2, cat: "DevOps", lessons: 25, unlocked: false },
    { id: "github", name: "GitHub Actions", icon: "🐙", diff: 2, cat: "DevOps", lessons: 25, unlocked: false },
    { id: "awk", name: "AWK", icon: "🪓", diff: 3, cat: "Text", lessons: 30, unlocked: false },
    { id: "sed", name: "sed", icon: "🔧", diff: 3, cat: "Text", lessons: 30, unlocked: false },
    { id: "tcl", name: "Tcl", icon: "🛠️", diff: 3, cat: "Scripting", lessons: 35, unlocked: false },
    { id: "qt", name: "Qt/QML", icon: "🔷", diff: 3, cat: "GUI", lessons: 40, unlocked: false },
    { id: "gtk", name: "GTK/Glade", icon: "🪟", diff: 3, cat: "GUI", lessons: 35, unlocked: false },
    { id: "opengl", name: "OpenGL/GLSL", icon: "🎮", diff: 4, cat: "Graphics", lessons: 50, unlocked: false },
    { id: "vulkan", name: "Vulkan/SPIR-V", icon: "🎮", diff: 5, cat: "Graphics", lessons: 55, unlocked: false },
    { id: "directx", name: "DirectX/HLSL", icon: "🎮", diff: 4, cat: "Graphics", lessons: 50, unlocked: false },
    { id: "webgl", name: "WebGL", icon: "🌐", diff: 3, cat: "Graphics", lessons: 40, unlocked: false },
    { id: "threejs", name: "Three.js", icon: "🎲", diff: 3, cat: "Graphics", lessons: 40, unlocked: false },
    { id: "unity", name: "Unity/C#", icon: "🎮", diff: 3, cat: "Game Dev", lessons: 50, unlocked: false },
    { id: "unreal", name: "Unreal/C++", icon: "🎮", diff: 4, cat: "Game Dev", lessons: 55, unlocked: false },
    { id: "godot", name: "Godot/GDScript", icon: "🎮", diff: 2, cat: "Game Dev", lessons: 40, unlocked: false },
    { id: "bevy", name: "Bevy/Rust", icon: "🎮", diff: 4, cat: "Game Dev", lessons: 50, unlocked: false },
    { id: "love2d", name: "LOVE2D", icon: "❤️", diff: 2, cat: "Game Dev", lessons: 35, unlocked: false },
    { id: "phaser", name: "Phaser.js", icon: "🎮", diff: 2, cat: "Game Dev", lessons: 35, unlocked: false },
    { id: "pygame", name: "Pygame", icon: "🐍", diff: 2, cat: "Game Dev", lessons: 35, unlocked: false },
    { id: "pico8", name: "PICO-8", icon: "🕹️", diff: 2, cat: "Game Dev", lessons: 30, unlocked: false },
    { id: "tic80", name: "TIC-80", icon: "🕹️", diff: 2, cat: "Game Dev", lessons: 30, unlocked: false },
    { id: "gbstudio", name: "GB Studio", icon: "🎮", diff: 2, cat: "Game Dev", lessons: 30, unlocked: false },
    { id: "rpgmaker", name: "RPG Maker", icon: "⚔️", diff: 1, cat: "Game Dev", lessons: 25, unlocked: false },
    { id: "gml", name: "GameMaker/GML", icon: "🎮", diff: 2, cat: "Game Dev", lessons: 35, unlocked: false },
    { id: "construct", name: "Construct", icon: "🧱", diff: 1, cat: "Game Dev", lessons: 25, unlocked: false },
    { id: "stencyl", name: "Stencyl", icon: "🧩", diff: 1, cat: "Game Dev", lessons: 25, unlocked: false },
    { id: "scratchjr", name: "ScratchJr", icon: "🐱", diff: 1, cat: "Visual", lessons: 15, unlocked: true },
    { id: "blockly", name: "Blockly", icon: "🧩", diff: 1, cat: "Visual", lessons: 20, unlocked: true },
    { id: "snap", name: "Snap!", icon: "📸", diff: 1, cat: "Visual", lessons: 20, unlocked: true },
    { id: "alice", name: "Alice", icon: "🐰", diff: 1, cat: "Visual", lessons: 20, unlocked: false },
    { id: "greenfoot", name: "Greenfoot", icon: "🐸", diff: 2, cat: "Education", lessons: 30, unlocked: false },
    { id: "processing", name: "Processing", icon: "🎨", diff: 2, cat: "Creative", lessons: 35, unlocked: false },
    { id: "p5js", name: "p5.js", icon: "🎨", diff: 2, cat: "Creative", lessons: 35, unlocked: false },
    { id: "openframeworks", name: "openFrameworks", icon: "🎨", diff: 3, cat: "Creative", lessons: 40, unlocked: false },
    { id: "maxmsp", name: "Max/MSP", icon: "🎵", diff: 3, cat: "Creative", lessons: 40, unlocked: false },
    { id: "puredata", name: "Pure Data", icon: "🎵", diff: 3, cat: "Creative", lessons: 40, unlocked: false },
    { id: "supercollider", name: "SuperCollider", icon: "🎵", diff: 4, cat: "Creative", lessons: 45, unlocked: false },
    { id: "sonicpi", name: "Sonic Pi", icon: "🎵", diff: 2, cat: "Creative", lessons: 30, unlocked: false },
    { id: "chucK", name: "ChucK", icon: "🎵", diff: 3, cat: "Creative", lessons: 40, unlocked: false },
    { id: "shader", name: "GLSL/HLSL", icon: "🎨", diff: 4, cat: "Graphics", lessons: 50, unlocked: false },
    { id: "opencl", name: "OpenCL", icon: "⚡", diff: 4, cat: "Compute", lessons: 50, unlocked: false },
    { id: "cuda", name: "CUDA", icon: "⚡", diff: 4, cat: "Compute", lessons: 50, unlocked: false },
    { id: "openmp", name: "OpenMP", icon: "🧵", diff: 3, cat: "Parallel", lessons: 40, unlocked: false },
    { id: "mpi", name: "MPI", icon: "🌐", diff: 4, cat: "Parallel", lessons: 45, unlocked: false },
    { id: "akka", name: "Akka", icon: "🎭", diff: 4, cat: "Actor", lessons: 45, unlocked: false },
    { id: "vertx", name: "Vert.x", icon: "📐", diff: 4, cat: "Reactive", lessons: 45, unlocked: false },
    { id: "rxjava", name: "RxJava", icon: "⚡", diff: 4, cat: "Reactive", lessons: 45, unlocked: false },
    { id: "rxjs", name: "RxJS", icon: "⚡", diff: 3, cat: "Reactive", lessons: 40, unlocked: false },
    { id: "coroutines", name: "Kotlin Coroutines", icon: "🧵", diff: 3, cat: "Async", lessons: 40, unlocked: false },
    { id: "asyncio", name: "Python asyncio", icon: "🐍", diff: 3, cat: "Async", lessons: 40, unlocked: false },
    { id: "nodejs", name: "Node.js", icon: "🟢", diff: 3, cat: "Runtime", lessons: 40, unlocked: false },
    { id: "deno", name: "Deno", icon: "🦕", diff: 3, cat: "Runtime", lessons: 35, unlocked: false },
    { id: "bun", name: "Bun", icon: "🥯", diff: 3, cat: "Runtime", lessons: 35, unlocked: false },
    { id: "spring", name: "Spring Boot", icon: "🌱", diff: 3, cat: "Framework", lessons: 45, unlocked: false },
    { id: "django", name: "Django", icon: "🎸", diff: 3, cat: "Framework", lessons: 45, unlocked: false },
    { id: "flask", name: "Flask", icon: "🌶️", diff: 2, cat: "Framework", lessons: 35, unlocked: false },
    { id: "fastapi", name: "FastAPI", icon: "⚡", diff: 2, cat: "Framework", lessons: 35, unlocked: false },
    { id: "express", name: "Express.js", icon: "🚂", diff: 2, cat: "Framework", lessons: 35, unlocked: false },
    { id: "nextjs", name: "Next.js", icon: "▲", diff: 3, cat: "Framework", lessons: 40, unlocked: false },
    { id: "nuxt", name: "Nuxt.js", icon: "🟢", diff: 3, cat: "Framework", lessons: 40, unlocked: false },
    { id: "svelte", name: "Svelte/SvelteKit", icon: "🔥", diff: 2, cat: "Framework", lessons: 35, unlocked: false },
    { id: "astro", name: "Astro", icon: "🚀", diff: 2, cat: "Framework", lessons: 35, unlocked: false },
    { id: "remix", name: "Remix", icon: "🎸", diff: 3, cat: "Framework", lessons: 40, unlocked: false },
    { id: "blazor", name: "Blazor", icon: "🔷", diff: 3, cat: "Framework", lessons: 40, unlocked: false },
    { id: "angular", name: "Angular", icon: "🅰️", diff: 3, cat: "Framework", lessons: 50, unlocked: false },
    { id: "react", name: "React", icon: "⚛️", diff: 3, cat: "Library", lessons: 45, unlocked: false },
    { id: "vue", name: "Vue.js", icon: "🟢", diff: 2, cat: "Framework", lessons: 40, unlocked: false },
    { id: "jquery", name: "jQuery", icon: "💲", diff: 1, cat: "Library", lessons: 25, unlocked: false },
    { id: "bootstrap", name: "Bootstrap", icon: "🅱️", diff: 1, cat: "CSS", lessons: 25, unlocked: false },
    { id: "tailwind", name: "Tailwind CSS", icon: "🌊", diff: 2, cat: "CSS", lessons: 30, unlocked: false },
    { id: "sass", name: "Sass/SCSS", icon: "🎀", diff: 2, cat: "CSS", lessons: 30, unlocked: false },
    { id: "flutter", name: "Flutter/Dart", icon: "🦋", diff: 3, cat: "Mobile", lessons: 45, unlocked: false },
    { id: "reactnative", name: "React Native", icon: "📱", diff: 3, cat: "Mobile", lessons: 45, unlocked: false },
    { id: "ionic", name: "Ionic", icon: "⚡", diff: 2, cat: "Mobile", lessons: 35, unlocked: false },
    { id: "xamarin", name: "Xamarin", icon: "📱", diff: 3, cat: "Mobile", lessons: 40, unlocked: false },
    { id: "arduino", name: "Arduino/C++", icon: "🔌", diff: 2, cat: "IoT", lessons: 35, unlocked: false },
    { id: "raspberrypi", name: "Raspberry Pi/Python", icon: "🍓", diff: 2, cat: "IoT", lessons: 35, unlocked: false },
    { id: "esp32", name: "ESP32/C++", icon: "📡", diff: 3, cat: "IoT", lessons: 40, unlocked: false },
    { id: "micropython", name: "MicroPython", icon: "🐍", diff: 2, cat: "IoT", lessons: 30, unlocked: false },
    { id: "zephyr", name: "Zephyr RTOS", icon: "🌬️", diff: 4, cat: "IoT", lessons: 45, unlocked: false },
    { id: "freertos", name: "FreeRTOS", icon: "⏱️", diff: 4, cat: "IoT", lessons: 45, unlocked: false },
    { id: "mqtt", name: "MQTT", icon: "📡", diff: 2, cat: "Protocol", lessons: 20, unlocked: false },
    { id: "lora", name: "LoRaWAN", icon: "📡", diff: 3, cat: "Protocol", lessons: 30, unlocked: false },
    { id: "ble", name: "Bluetooth LE", icon: "📡", diff: 3, cat: "Protocol", lessons: 30, unlocked: false },
    { id: "zigbee", name: "Zigbee", icon: "🐝", diff: 3, cat: "Protocol", lessons: 30, unlocked: false },
    { id: "matter", name: "Matter/Thread", icon: "🔗", diff: 3, cat: "Protocol", lessons: 30, unlocked: false },
    { id: "alexa", name: "Alexa Skills", icon: "🔊", diff: 2, cat: "Voice", lessons: 25, unlocked: false },
    { id: "dialogflow", name: "Dialogflow", icon: "💬", diff: 2, cat: "NLP", lessons: 25, unlocked: false },
    { id: "rasa", name: "Rasa", icon: "🤖", diff: 3, cat: "NLP", lessons: 35, unlocked: false },
    { id: "spacy", name: "spaCy", icon: "🐍", diff: 3, cat: "NLP", lessons: 35, unlocked: false },
    { id: "nltk", name: "NLTK", icon: "🐍", diff: 3, cat: "NLP", lessons: 35, unlocked: false },
    { id: "transformers", name: "Hugging Face", icon: "🤗", diff: 3, cat: "ML", lessons: 40, unlocked: false },
    { id: "tensorflow", name: "TensorFlow", icon: "🧠", diff: 3, cat: "ML", lessons: 45, unlocked: false },
    { id: "pytorch", name: "PyTorch", icon: "🔥", diff: 3, cat: "ML", lessons: 45, unlocked: false },
    { id: "keras", name: "Keras", icon: "🧠", diff: 2, cat: "ML", lessons: 35, unlocked: false },
    { id: "jax", name: "JAX", icon: "⚡", diff: 4, cat: "ML", lessons: 45, unlocked: false },
    { id: "opencv", name: "OpenCV", icon: "👁️", diff: 3, cat: "CV", lessons: 40, unlocked: false },
    { id: "scikit", name: "scikit-learn", icon: "🧪", diff: 3, cat: "ML", lessons: 40, unlocked: false },
    { id: "pandas", name: "Pandas", icon: "🐼", diff: 2, cat: "Data", lessons: 30, unlocked: false },
    { id: "numpy", name: "NumPy", icon: "🔢", diff: 2, cat: "Data", lessons: 30, unlocked: false },
    { id: "matplotlib", name: "Matplotlib", icon: "📊", diff: 2, cat: "Data", lessons: 25, unlocked: false },
    { id: "seaborn", name: "Seaborn", icon: "🌊", diff: 2, cat: "Data", lessons: 25, unlocked: false },
    { id: "plotly", name: "Plotly", icon: "📈", diff: 2, cat: "Data", lessons: 25, unlocked: false },
    { id: "d3", name: "D3.js", icon: "📊", diff: 4, cat: "Data Viz", lessons: 50, unlocked: false },
    { id: "tableau", name: "Tableau", icon: "📊", diff: 2, cat: "BI", lessons: 30, unlocked: false },
    { id: "powerbi", name: "Power BI/DAX", icon: "📊", diff: 2, cat: "BI", lessons: 30, unlocked: false },
    { id: "spark", name: "Apache Spark", icon: "⚡", diff: 4, cat: "Big Data", lessons: 50, unlocked: false },
    { id: "hadoop", name: "Hadoop", icon: "🐘", diff: 4, cat: "Big Data", lessons: 45, unlocked: false },
    { id: "kafka", name: "Apache Kafka", icon: "📨", diff: 4, cat: "Streaming", lessons: 45, unlocked: false },
    { id: "flink", name: "Apache Flink", icon: "🌊", diff: 4, cat: "Streaming", lessons: 45, unlocked: false },
    { id: "cassandra", name: "Cassandra/CQL", icon: "🏛️", diff: 3, cat: "Database", lessons: 40, unlocked: false },
    { id: "mongodb", name: "MongoDB", icon: "🍃", diff: 2, cat: "Database", lessons: 35, unlocked: false },
    { id: "redis", name: "Redis", icon: "🔴", diff: 2, cat: "Database", lessons: 25, unlocked: false },
    { id: "elasticsearch", name: "Elasticsearch", icon: "🔍", diff: 3, cat: "Search", lessons: 40, unlocked: false },
    { id: "neo4j", name: "Neo4j/Cypher", icon: "🕸️", diff: 3, cat: "Graph", lessons: 40, unlocked: false },
    { id: "influxdb", name: "InfluxDB/Flux", icon: "📈", diff: 3, cat: "Time Series", lessons: 35, unlocked: false },
    { id: "prometheus", name: "Prometheus/PromQL", icon: "📊", diff: 3, cat: "Monitoring", lessons: 35, unlocked: false },
    { id: "grafana", name: "Grafana", icon: "📊", diff: 2, cat: "Monitoring", lessons: 25, unlocked: false },
    { id: "nginx", name: "Nginx Config", icon: "🌐", diff: 2, cat: "Proxy", lessons: 25, unlocked: false },
    { id: "apache", name: "Apache Config", icon: "🪶", diff: 2, cat: "Server", lessons: 25, unlocked: false },
    { id: "caddy", name: "Caddyfile", icon: "🚗", diff: 1, cat: "Proxy", lessons: 20, unlocked: false },
    { id: "istio", name: "Istio", icon: "🌐", diff: 4, cat: "Service Mesh", lessons: 45, unlocked: false },
    { id: "linkerd", name: "Linkerd", icon: "🔗", diff: 4, cat: "Service Mesh", lessons: 45, unlocked: false },
    { id: "envoy", name: "Envoy", icon: "🛡️", diff: 4, cat: "Proxy", lessons: 45, unlocked: false },
    { id: "consul", name: "Consul", icon: "🏛️", diff: 3, cat: "Service Mesh", lessons: 40, unlocked: false },
    { id: "kubernetes", name: "Kubernetes", icon: "☸️", diff: 4, cat: "Orchestration", lessons: 50, unlocked: false },
    { id: "docker", name: "Docker", icon: "🐳", diff: 2, cat: "Container", lessons: 30, unlocked: false },
    { id: "podman", name: "Podman", icon: "🦭", diff: 2, cat: "Container", lessons: 25, unlocked: false },
    { id: "helm", name: "Helm", icon: "⛵", diff: 3, cat: "Package", lessons: 30, unlocked: false },
    { id: "kustomize", name: "Kustomize", icon: "🔧", diff: 3, cat: "Config", lessons: 30, unlocked: false },
    { id: "argocd", name: "ArgoCD", icon: "🐙", diff: 3, cat: "GitOps", lessons: 35, unlocked: false },
    { id: "fluxcd", name: "FluxCD", icon: "⚡", diff: 3, cat: "GitOps", lessons: 35, unlocked: false },
    { id: "spinnaker", name: "Spinnaker", icon: "🎡", diff: 4, cat: "CD", lessons: 45, unlocked: false },
    { id: "tekton", name: "Tekton", icon: "🔧", diff: 3, cat: "CI/CD", lessons: 40, unlocked: false },
    { id: "argo", name: "Argo Workflows", icon: "🐙", diff: 3, cat: "Workflow", lessons: 40, unlocked: false },
    { id: "airflow", name: "Apache Airflow", icon: "🌬️", diff: 3, cat: "Workflow", lessons: 40, unlocked: false },
    { id: "prefect", name: "Prefect", icon: "🌊", diff: 3, cat: "Workflow", lessons: 35, unlocked: false },
    { id: "dagster", name: "Dagster", icon: "🎯", diff: 3, cat: "Workflow", lessons: 35, unlocked: false },
    { id: "dbt", name: "dbt", icon: "🧱", diff: 2, cat: "Data", lessons: 30, unlocked: false },
    { id: "snowflake", name: "Snowflake/SQL", icon: "❄️", diff: 3, cat: "Data Warehouse", lessons: 40, unlocked: false },
    { id: "bigquery", name: "BigQuery/SQL", icon: "📊", diff: 3, cat: "Data Warehouse", lessons: 40, unlocked: false },
    { id: "redshift", name: "Redshift/SQL", icon: "📊", diff: 3, cat: "Data Warehouse", lessons: 40, unlocked: false },
    { id: "databricks", name: "Databricks", icon: "⚡", diff: 3, cat: "Data", lessons: 40, unlocked: false },
    { id: "synapse", name: "Azure Synapse", icon: "☁️", diff: 3, cat: "Data", lessons: 40, unlocked: false },
    { id: "fabric", name: "Microsoft Fabric", icon: "🧵", diff: 3, cat: "Data", lessons: 40, unlocked: false },
    { id: "dremio", name: "Dremio", icon: "🦕", diff: 3, cat: "Data", lessons: 35, unlocked: false },
    { id: "trino", name: "Trino/Presto", icon: "🐿️", diff: 4, cat: "Query", lessons: 45, unlocked: false },
    { id: "hive", name: "Hive/HQL", icon: "🐝", diff: 3, cat: "Query", lessons: 40, unlocked: false },
    { id: "pig", name: "Pig Latin", icon: "🐷", diff: 3, cat: "Query", lessons: 35, unlocked: false },
    { id: "drill", name: "Apache Drill", icon: "🔩", diff: 3, cat: "Query", lessons: 35, unlocked: false },
    { id: "impala", name: "Impala", icon: "🦌", diff: 3, cat: "Query", lessons: 35, unlocked: false },
    { id: "phoenix", name: "Apache Phoenix", icon: "🔥", diff: 3, cat: "Query", lessons: 35, unlocked: false },
    { id: "calcite", name: "Apache Calcite", icon: "🧮", diff: 4, cat: "Query", lessons: 45, unlocked: false },
    { id: "arrow", name: "Apache Arrow", icon: "➡️", diff: 3, cat: "Data", lessons: 35, unlocked: false },
    { id: "parquet", name: "Parquet", icon: "📦", diff: 2, cat: "Data", lessons: 20, unlocked: false },
    { id: "avro", name: "Avro", icon: "🐦", diff: 2, cat: "Data", lessons: 20, unlocked: false },
    { id: "protobuf", name: "Protocol Buffers", icon: "📦", diff: 2, cat: "Data", lessons: 25, unlocked: false },
    { id: "thrift", name: "Thrift", icon: "🎁", diff: 2, cat: "RPC", lessons: 25, unlocked: false },
    { id: "grpc", name: "gRPC", icon: "🌐", diff: 3, cat: "RPC", lessons: 35, unlocked: false },
    { id: "graphqlfederation", name: "GraphQL Federation", icon: "🌐", diff: 4, cat: "API", lessons: 45, unlocked: false },
    { id: "rest", name: "REST API Design", icon: "🌐", diff: 2, cat: "API", lessons: 25, unlocked: false },
    { id: "openapi", name: "OpenAPI/Swagger", icon: "📋", diff: 2, cat: "API", lessons: 25, unlocked: false },
    { id: "postman", name: "Postman/Collections", icon: "🚀", diff: 1, cat: "API", lessons: 15, unlocked: false },
    { id: "insomnia", name: "Insomnia", icon: "😴", diff: 1, cat: "API", lessons: 15, unlocked: false },
    { id: "hoppscotch", name: "Hoppscotch", icon: "🦘", diff: 1, cat: "API", lessons: 15, unlocked: false },
    { id: "soap", name: "SOAP/WSDL", icon: "🧼", diff: 3, cat: "API", lessons: 30, unlocked: false },
    { id: "odata", name: "OData", icon: "📊", diff: 3, cat: "API", lessons: 30, unlocked: false },
    { id: "jsonschema", name: "JSON Schema", icon: "📋", diff: 2, cat: "Data", lessons: 20, unlocked: false },
    { id: "xmlschema", name: "XML Schema/XSD", icon: "📄", diff: 3, cat: "Data", lessons: 25, unlocked: false },
    { id: "xpath", name: "XPath", icon: "🔍", diff: 3, cat: "XML", lessons: 25, unlocked: false },
    { id: "xslt", name: "XSLT", icon: "🔄", diff: 3, cat: "XML", lessons: 30, unlocked: false },
    { id: "selenium", name: "Selenium", icon: "🧪", diff: 2, cat: "Testing", lessons: 30, unlocked: false },
    { id: "cypress", name: "Cypress", icon: "🌲", diff: 2, cat: "Testing", lessons: 30, unlocked: false },
    { id: "playwright", name: "Playwright", icon: "🎭", diff: 2, cat: "Testing", lessons: 30, unlocked: false },
    { id: "jest", name: "Jest", icon: "🃏", diff: 2, cat: "Testing", lessons: 25, unlocked: false },
    { id: "mocha", name: "Mocha", icon: "☕", diff: 2, cat: "Testing", lessons: 25, unlocked: false },
    { id: "pytest", name: "pytest", icon: "🐍", diff: 2, cat: "Testing", lessons: 25, unlocked: false },
    { id: "junit", name: "JUnit", icon: "☕", diff: 2, cat: "Testing", lessons: 25, unlocked: false },
    { id: "cucumber", name: "Cucumber/Gherkin", icon: "🥒", diff: 2, cat: "BDD", lessons: 25, unlocked: false },
    { id: "robot", name: "Robot Framework", icon: "🤖", diff: 2, cat: "Testing", lessons: 25, unlocked: false },
    { id: "jmeter", name: "JMeter", icon: "⚡", diff: 2, cat: "Testing", lessons: 25, unlocked: false },
    { id: "gatling", name: "Gatling", icon: "🔫", diff: 3, cat: "Performance", lessons: 30, unlocked: false },
    { id: "locust", name: "Locust", icon: "🦗", diff: 2, cat: "Performance", lessons: 25, unlocked: false },
    { id: "k6", name: "k6", icon: "⚡", diff: 2, cat: "Performance", lessons: 25, unlocked: false },
    { id: "lighthouse", name: "Lighthouse", icon: "🗼", diff: 1, cat: "Performance", lessons: 15, unlocked: false },
    { id: "owasp", name: "OWASP Top 10", icon: "🛡️", diff: 3, cat: "Security", lessons: 30, unlocked: false },
    { id: "oauth", name: "OAuth 2.0", icon: "🔑", diff: 3, cat: "Security", lessons: 25, unlocked: false },
    { id: "oidc", name: "OpenID Connect", icon: "🔑", diff: 3, cat: "Security", lessons: 25, unlocked: false },
    { id: "saml", name: "SAML", icon: "📜", diff: 3, cat: "Security", lessons: 25, unlocked: false },
    { id: "jwt", name: "JWT", icon: "🎫", diff: 2, cat: "Security", lessons: 20, unlocked: false },
    { id: "rbac", name: "RBAC", icon: "👥", diff: 2, cat: "Security", lessons: 20, unlocked: false },
    { id: "abac", name: "ABAC", icon: "👥", diff: 3, cat: "Security", lessons: 25, unlocked: false },
    { id: "opa", name: "Open Policy Agent", icon: "🛡️", diff: 3, cat: "Security", lessons: 30, unlocked: false },
    { id: "falco", name: "Falco", icon: "🦅", diff: 3, cat: "Security", lessons: 30, unlocked: false },
    { id: "trivy", name: "Trivy", icon: "🔍", diff: 2, cat: "Security", lessons: 20, unlocked: false },
    { id: "snyk", name: "Snyk", icon: "🐕", diff: 2, cat: "Security", lessons: 20, unlocked: false },
    { id: "sonarqube", name: "SonarQube", icon: "📊", diff: 2, cat: "Quality", lessons: 25, unlocked: false },
    { id: "codeclimate", name: "Code Climate", icon: "🌤️", diff: 2, cat: "Quality", lessons: 20, unlocked: false },
    { id: "codacy", name: "Codacy", icon: "📊", diff: 2, cat: "Quality", lessons: 20, unlocked: false },
    { id: "codecov", name: "Codecov", icon: "📊", diff: 2, cat: "Quality", lessons: 20, unlocked: false },
    { id: "coveralls", name: "Coveralls", icon: "📊", diff: 2, cat: "Quality", lessons: 15, unlocked: false },
    { id: "deepsource", name: "DeepSource", icon: "🔍", diff: 2, cat: "Quality", lessons: 20, unlocked: false },
    { id: "semgrep", name: "Semgrep", icon: "🔍", diff: 2, cat: "Security", lessons: 20, unlocked: false },
    { id: "bandit", name: "Bandit", icon: "🐍", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "brakeman", name: "Brakeman", icon: "🚂", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "gosec", name: "gosec", icon: "🔒", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "tfsec", name: "tfsec", icon: "🏗️", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "checkov", name: "Checkov", icon: "✅", diff: 2, cat: "Security", lessons: 20, unlocked: false },
    { id: "terrascan", name: "Terrascan", icon: "🔍", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "snykcontainer", name: "Snyk Container", icon: "🐳", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "anchore", name: "Anchore", icon: "⚓", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "clair", name: "Clair", icon: "🔍", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "grype", name: "Grype", icon: "🔍", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "syft", name: "Syft", icon: "📦", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "cosign", name: "Cosign", icon: "✍️", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "notation", name: "Notation", icon: "🎵", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "sigstore", name: "Sigstore", icon: "🔏", diff: 3, cat: "Security", lessons: 20, unlocked: false },
    { id: "rekor", name: "Rekor", icon: "📜", diff: 3, cat: "Security", lessons: 20, unlocked: false },
    { id: "fulcio", name: "Fulcio", icon: "📜", diff: 3, cat: "Security", lessons: 20, unlocked: false },
    { id: "keylime", name: "Keylime", icon: "🍋", diff: 3, cat: "Security", lessons: 20, unlocked: false },
    { id: "in-toto", name: "in-toto", icon: "🔗", diff: 3, cat: "Security", lessons: 20, unlocked: false },
    { id: "slsa", name: "SLSA", icon: "🏗️", diff: 3, cat: "Security", lessons: 20, unlocked: false },
    { id: "spdx", name: "SPDX", icon: "📋", diff: 2, cat: "Compliance", lessons: 15, unlocked: false },
    { id: "cyclonedx", name: "CycloneDX", icon: "🌀", diff: 2, cat: "Compliance", lessons: 15, unlocked: false },
    { id: "swid", name: "SWID", icon: "📋", diff: 2, cat: "Compliance", lessons: 15, unlocked: false },
    { id: "cve", name: "CVE", icon: "🐛", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "cvss", name: "CVSS", icon: "📊", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "epss", name: "EPSS", icon: "📊", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "cwe", name: "CWE", icon: "🐛", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "capec", name: "CAPEC", icon: "🎯", diff: 2, cat: "Security", lessons: 15, unlocked: false },
    { id: "mitre", name: "MITRE ATT&CK", icon: "🎯", diff: 3, cat: "Security", lessons: 25, unlocked: false },
    { id: "nist", name: "NIST CSF", icon: "🏛️", diff: 3, cat: "Security", lessons: 25, unlocked: false },
    { id: "iso27001", name: "ISO 27001", icon: "📜", diff: 3, cat: "Compliance", lessons: 25, unlocked: false },
    { id: "soc2", name: "SOC 2", icon: "📜", diff: 3, cat: "Compliance", lessons: 25, unlocked: false },
    { id: "gdpr", name: "GDPR", icon: "🇪🇺", diff: 3, cat: "Compliance", lessons: 25, unlocked: false },
    { id: "hipaa", name: "HIPAA", icon: "🏥", diff: 3, cat: "Compliance", lessons: 25, unlocked: false },
    { id: "pci", name: "PCI DSS", icon: "💳", diff: 3, cat: "Compliance", lessons: 25, unlocked: false },
    { id: "ferpa", name: "FERPA", icon: "🎓", diff: 2, cat: "Compliance", lessons: 20, unlocked: false },
    { id: "ccpa", name: "CCPA", icon: "🇺🇸", diff: 2, cat: "Compliance", lessons: 20, unlocked: false }
  ],

  gitSkillsDB: [
    { id: "init", name: "git init", icon: "📦", unlocked: true, xpReq: 0 },
    { id: "add", name: "git add", icon: "➕", unlocked: false, xpReq: 50 },
    { id: "commit", name: "git commit", icon: "📝", unlocked: false, xpReq: 100 },
    { id: "branch", name: "git branch", icon: "🌿", unlocked: false, xpReq: 200 },
    { id: "merge", name: "git merge", icon: "🔀", unlocked: false, xpReq: 350 },
    { id: "rebase", name: "git rebase", icon: "🔄", unlocked: false, xpReq: 500 },
    { id: "stash", name: "git stash", icon: "📥", unlocked: false, xpReq: 400 },
    { id: "cherrypick", name: "git cherry-pick", icon: "🍒", unlocked: false, xpReq: 600 },
    { id: "bisect", name: "git bisect", icon: "🔍", unlocked: false, xpReq: 800 },
    { id: "hooks", name: "git hooks", icon: "🪝", unlocked: false, xpReq: 1000 }
  ],

  quests: [
    { id: 1, name: "The Seed", desc: "Hello World in 10 languages", reward: 100, completed: true },
    { id: 2, name: "The Forge", desc: "Build a calculator app", reward: 250, completed: false },
    { id: 3, name: "The Merge", desc: "Resolve a git conflict", reward: 400, completed: false },
    { id: 4, name: "Titan's Crown", desc: "Full-stack in 5 languages", reward: 1000, completed: false },
    { id: 5, name: "Codyssey Master", desc: "Contribute to open source", reward: 2000, completed: false }
  ],

  addXP(amount) {
    this.player.xp += amount;
    this.checkLevelUp();
    this.saveProgress();
  },

  checkLevelUp() {
    const req = this.player.level * 500;
    if (this.player.xp >= req) {
      this.player.level++;
      this.player.xp -= req;
      this.unlockRewards();
      return true;
    }
    return false;
  },

  unlockRewards() {
    this.gitSkillsDB.forEach(skill => {
      if (!skill.unlocked && this.player.xp >= skill.xpReq) {
        skill.unlocked = true;
        this.player.gitSkillsUnlocked.push(skill.id);
      }
    });
  },

  saveProgress() {
    localStorage.setItem('titanProgress', JSON.stringify(this.player));
  },

  loadProgress() {
    const saved = localStorage.getItem('titanProgress');
    if (saved) this.player = JSON.parse(saved);
  },

  runCode(lang, code) {
    const outputs = {
      python: code.includes('print') ? code.match(/print\\((["\'])(.+?)\\1/)?.[2] || 'Output' : 'Executed!',
      javascript: code.includes('console.log') ? code.match(/console\\.log\\((["\'])(.+?)\\1/)?.[2] || 'Output' : 'Executed!',
      java: 'Compiled successfully!',
      cpp: 'Compiled successfully!'
    };
    return outputs[lang] || 'Language not supported yet!';
  }
};
''')
